# Generated by Django 5.0.6 on 2024-07-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_payment_course_author_lesson_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
